//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteProjet.Models.LocalDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRENEAUX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRENEAUX()
        {
            this.RV = new HashSet<RV>();
        }
    
        public long ID { get; set; }
        public Nullable<int> HDEBUT { get; set; }
        public Nullable<int> MDEBUT { get; set; }
        public Nullable<int> HFIN { get; set; }
        public Nullable<int> MFIN { get; set; }
        public Nullable<long> ID_MEDECIN { get; set; }
    
        public virtual MEDECINS MEDECINS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RV> RV { get; set; }
    }
}
