//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteProjet.Models.LocalDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBRDVMEDECINSEntities : DbContext
    {
        public DBRDVMEDECINSEntities()
            : base("name=DBRDVMEDECINSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTS> CLIENTS { get; set; }
        public virtual DbSet<CRENEAUX> CRENEAUX { get; set; }
        public virtual DbSet<MEDECINS> MEDECINS { get; set; }
        public virtual DbSet<RV> RV { get; set; }
    }
}
